# 기존 한글 도메인의 인증서가 준비된 후 적용합니다.
server {
    listen 80;
    listen [::]:80;
    listen 10.0.0.114:443 ssl;
    server_name xn--qn1bv2fnb48zez1asij.xn--h32bi4v.xn--3e0b707e;
    ssl_certificate /etc/letsencrypt/live/aram-legacy/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aram-legacy/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    location ^~ /.well-known/acme-challenge/ { root /var/www/letsencrypt; }
    location / { return 301 https://aram.c99-dev.com$request_uri; }
}
